#!/usr/bin/env bash

#
# Installer
#

echo 'Removing old bundles...'
rm -rf ~/.vim/bundle

echo 'Setting vimrc...'
ln -sf ~/.vim/vimrc ~/.vimrc

echo 'Cloning vundle...'
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo 'Installing vim plugins...'
vim +PluginInstall +qall

echo 'Done.'

